readshm.o writeshm.o readnum.o writenum.o: readshm.c writeshm.c readnum.c writenum.c
	gcc readshm.c -Wall -g -o readshm.o
	gcc readnum.c -Wall -g -o readnum.o
	gcc writeshm.c -Wall -g -o writeshm.o
	gcc writenum.c -Wall -g -o writenum.o

clean:
	rm *.o
